/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package family_dental_care;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thoma
 */
public class manager_treatment_book extends javax.swing.JFrame {

    /**
     * Creates new form manager_treatment_book
     */
    public manager_treatment_book() {
        initComponents();
        doctoridcombobox();
        autoID();
        treatmentidcombobox();
        patientidcombobox();
        sort();
        RefrushTable();
        
        
        Toolkit toolkit=getToolkit();
    Dimension size=toolkit.getScreenSize();
    setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    
    ImageIcon logo_im=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    Image img1_logo=logo_im.getImage();
    Image img2_logo=img1_logo.getScaledInstance(logo.getWidth(),logo.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon a=new ImageIcon(img2_logo);
    logo.setIcon(a);
    
    ImageIcon home_im=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("home.png")));
    Image img1_home=home_im.getImage();
    Image img2_home=img1_home.getScaledInstance(home.getWidth(),home.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon b=new ImageIcon(img2_home);
    home.setIcon(b);
    
    
    //resize close button 
    ImageIcon close_img=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("close.png")));
    Image img1_close=close_img.getImage();
    Image img2_close=img1_close.getScaledInstance(close.getWidth(),close.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon c=new ImageIcon(img2_close);
    close.setIcon(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        treatmentbookid = new javax.swing.JTextField();
        treatmentid = new javax.swing.JComboBox<>();
        patientid = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        treatmentbook_table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        doctorid = new javax.swing.JComboBox<>();
        startdate = new javax.swing.JTextField();
        enddate = new javax.swing.JTextField();
        clear_treatmentbook = new javax.swing.JButton();
        search_treatmentbook = new javax.swing.JButton();
        insert_treatmentbook = new javax.swing.JButton();
        update_treatmentbook = new javax.swing.JButton();
        delete_treatmentbook = new javax.swing.JButton();
        home = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(87, 194, 213));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setText("Treatment Book");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel11.setText("Treatment Book ID");

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel13.setText("Treatment ID");

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel14.setText("Patient ID");

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel15.setText("Doctor ID");

        treatmentbookid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        treatmentbookid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treatmentbookidMouseClicked(evt);
            }
        });
        treatmentbookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentbookidActionPerformed(evt);
            }
        });
        treatmentbookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                treatmentbookidKeyReleased(evt);
            }
        });

        treatmentid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        treatmentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentidActionPerformed(evt);
            }
        });

        patientid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        patientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientidActionPerformed(evt);
            }
        });

        treatmentbook_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Treatment ID", "Patient ID", "Start Date", "End Date", "Doctor ID", "Status"
            }
        ));
        treatmentbook_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treatmentbook_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treatmentbook_table);

        jLabel38.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel38.setText("            Doctor");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel39.setText("            Patient");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel40.setText("      Appointment");
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel41.setText("              Staff");
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel42.setText("         Treatment");
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel43.setText("             Room");
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel44.setText("    Treatment Book");
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel45.setText("        Room Book");
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel46.setText("           Payment");
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDateChooser2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jDateChooser2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser2KeyReleased(evt);
            }
        });

        jDateChooser3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jDateChooser3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser3KeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel16.setText("Start Date");

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel17.setText("End Date");

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel18.setText("Status");

        status.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                statusKeyReleased(evt);
            }
        });

        doctorid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        doctorid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctoridActionPerformed(evt);
            }
        });

        startdate.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        startdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startdateActionPerformed(evt);
            }
        });
        startdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                startdateKeyReleased(evt);
            }
        });

        enddate.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        enddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enddateActionPerformed(evt);
            }
        });
        enddate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                enddateKeyReleased(evt);
            }
        });

        clear_treatmentbook.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        clear_treatmentbook.setText("clear");
        clear_treatmentbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_treatmentbookMouseClicked(evt);
            }
        });
        clear_treatmentbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_treatmentbookActionPerformed(evt);
            }
        });

        search_treatmentbook.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        search_treatmentbook.setText("search");
        search_treatmentbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_treatmentbookMouseClicked(evt);
            }
        });
        search_treatmentbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_treatmentbookActionPerformed(evt);
            }
        });

        insert_treatmentbook.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        insert_treatmentbook.setText("insert");
        insert_treatmentbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insert_treatmentbookMouseClicked(evt);
            }
        });
        insert_treatmentbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_treatmentbookActionPerformed(evt);
            }
        });

        update_treatmentbook.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        update_treatmentbook.setText("update");
        update_treatmentbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_treatmentbookMouseClicked(evt);
            }
        });
        update_treatmentbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_treatmentbookActionPerformed(evt);
            }
        });

        delete_treatmentbook.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        delete_treatmentbook.setText("delete");
        delete_treatmentbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_treatmentbookMouseClicked(evt);
            }
        });
        delete_treatmentbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_treatmentbookActionPerformed(evt);
            }
        });

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(treatmentbookid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(treatmentid, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patientid, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startdate))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(status, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctorid, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enddate)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(clear_treatmentbook, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delete_treatmentbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(update_treatmentbook)
                                            .addComponent(insert_treatmentbook, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(search_treatmentbook, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear_treatmentbook, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(treatmentbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(doctorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(insert_treatmentbook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(update_treatmentbook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delete_treatmentbook))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(treatmentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_treatmentbook))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enddate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //doctor id for combo box
    private void doctoridcombobox(){
       try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
               PreparedStatement ps1=con.prepareStatement("select * from doctor");
               ResultSet rs=ps1.executeQuery();
               while(rs.next()){
                  doctorid.addItem(rs.getString("doctorid"));
               }
         }
         catch(Exception ex){
                   JOptionPane.showMessageDialog(null,"no id is there..");    
         }
    }
    
    //treatment id for combo box
    private void treatmentidcombobox(){
       try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
               PreparedStatement ps1=con.prepareStatement("select * from treatment");
               ResultSet rs=ps1.executeQuery();
               while(rs.next()){
                  treatmentid.addItem(rs.getString("treatmentid"));
               }
         }
         catch(Exception ex){
                   JOptionPane.showMessageDialog(null,"no id is there..");    
         }
    }
    //patient id for combo box
    private void patientidcombobox(){
       try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
               PreparedStatement ps1=con.prepareStatement("select * from patient");
               ResultSet rs=ps1.executeQuery();
               while(rs.next()){
                  patientid.addItem(rs.getString("patientid"));
               }
         }
         catch(Exception ex){
                   JOptionPane.showMessageDialog(null,"no id is there..");    
         }
    }
    //genarate auto ID
    private void autoID(){
        try{
        connection mysql=new connection();
        Connection con=mysql.connectDB();
        PreparedStatement selectdata=con.prepareStatement("SELECT treatmentbookid FROM treatment_book ORDER BY treatmentbookid DESC LIMIT 1");
        ResultSet rs=selectdata.executeQuery();
        if(rs.next()){
           String rnno=rs.getString("treatmentbookid");
           int co=rnno.length();
           String txt= rnno.substring(0, 4);
           String num=rnno.substring(4, co);
           int n=Integer.parseInt(num);
           n++;
           String snum=Integer.toString(n);
           String ftxt=txt+snum;
           treatmentbookid.setText(ftxt);
        }
        else{
           treatmentbookid.setText("TB001");
        }
        }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null,"no id is there..");
        }
    }
    
    private void RefrushTable(){
    try{
         connection mysql=new connection();
         Connection con=mysql.connectDB();
         PreparedStatement ps1=con.prepareStatement("SELECT * FROM treatment_book");
         ResultSet rs=ps1.executeQuery();
         DefaultTableModel model=(DefaultTableModel)treatmentbook_table.getModel();
         model.setRowCount(0);
         while(rs.next()){
           String treatmentbook_id =rs.getString("treatmentbookid");
           String treatment_id =rs.getString("treatmentid");
           String patient_id=rs.getString("patientid");
           String doctor_id=rs.getString("doctorid");
           String start_date=rs.getString("start_date");
           String end_date=rs.getString("end_date");
           String treat_status=rs.getString("status");
           //create array for store data into patient_table
           String tbData[]={treatmentbook_id,treatment_id,doctor_id,patient_id,start_date,end_date,treat_status};
           DefaultTableModel tb1Model=(DefaultTableModel)treatmentbook_table.getModel();
           //add string array data to table
           tb1Model.addRow(tbData);                   
         }
         
        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null,"error happen.please try again..");
         autoID();
        }
    }
    private void sort(){
       DefaultTableModel model=(DefaultTableModel)treatmentbook_table.getModel();    
       TableRowSorter sorter=new TableRowSorter(model);
       treatmentbook_table.setRowSorter(sorter);
    }
    //Filter table with sorting object
    private void filter(String query){
       //sorting the table values
       DefaultTableModel model=(DefaultTableModel)treatmentbook_table.getModel();    
       TableRowSorter sorter=new TableRowSorter(model);
       treatmentbook_table.setRowSorter(sorter);
       sorter.setRowFilter(RowFilter.regexFilter(query));
       
    }
    private void treatmentbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentbookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentbookidActionPerformed

    private void treatmentbookidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_treatmentbookidKeyReleased

    }//GEN-LAST:event_treatmentbookidKeyReleased

    private void treatmentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentidActionPerformed

    private void patientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientidActionPerformed

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        new manager_doctor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
        new patient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
        new manager_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel41MouseClicked

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void statusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_statusKeyReleased

    private void doctoridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctoridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctoridActionPerformed

    private void startdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startdateActionPerformed

    private void startdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startdateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_startdateKeyReleased

    private void enddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enddateActionPerformed

    private void enddateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enddateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_enddateKeyReleased

    private void jDateChooser2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser2KeyReleased
        // TODO add your handling code here:
        String start_date=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        startdate.setText(start_date);
    }//GEN-LAST:event_jDateChooser2KeyReleased

    private void jDateChooser3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser3KeyReleased
        // TODO add your handling code here:
        String end_date=((JTextField)jDateChooser3.getDateEditor().getUiComponent()).getText();
        enddate.setText(end_date);
    }//GEN-LAST:event_jDateChooser3KeyReleased

    private void jDateChooser3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser3KeyPressed
        // TODO add your handling code here:
        String start_date=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        startdate.setText(start_date);
    }//GEN-LAST:event_jDateChooser3KeyPressed

    private void clear_treatmentbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_treatmentbookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_treatmentbookMouseClicked

    private void clear_treatmentbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_treatmentbookActionPerformed
        // TODO add your handling code here:
              autoID();
              treatmentid.setSelectedItem(null);
              doctorid.setSelectedItem(null);
              patientid.setSelectedItem(null);
              jDateChooser2.setDate(null);
              jDateChooser3.setDate(null);
              status.setText(null);
        

    }//GEN-LAST:event_clear_treatmentbookActionPerformed

    private void search_treatmentbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_treatmentbookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_search_treatmentbookMouseClicked

    private void search_treatmentbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_treatmentbookActionPerformed
        // TODO add your handling code here:
        String treatmentbook_id=treatmentbookid.getText();
        if(treatmentbookid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"All fields are required..");
        }
        else{
           try{
              connection mysql=new connection();
              Connection con=mysql.connectDB();
            
              PreparedStatement selectdata=con.prepareStatement("select * from treatment_book where treatmentbookid=?");
              selectdata.setString(1,treatmentbook_id);
              ResultSet rs=selectdata.executeQuery();
              if(rs.next()){
                  treatmentbookid.setText(treatmentbook_id);
                  String treatment_id=rs.getString("treatmentid");
                  treatmentid.setSelectedItem(treatment_id);
                  String doctor_id=rs.getString("doctorid");
                  doctorid.setSelectedItem(doctor_id);
                  String patient_id=rs.getString("patientid");
                  patientid.setSelectedItem(patient_id);
                  startdate.setText(rs.getString("start_date"));
                  enddate.setText(rs.getString("end_date"));
                  status.setText(rs.getString("status"));
              }
           }
           catch(Exception ex){
               
           }
        }
    }//GEN-LAST:event_search_treatmentbookActionPerformed

    private void insert_treatmentbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_treatmentbookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_insert_treatmentbookMouseClicked

    private void insert_treatmentbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_treatmentbookActionPerformed
        // TODO add your handling code here:
        String treatmentbook_id=treatmentbookid.getText();
        if(treatmentbookid.getText().equals("") || status.getText().equals("")){
            JOptionPane.showMessageDialog(null,"All fields are required..");
        }
        else{
            try{
               connection mysql=new connection();
              Connection con=mysql.connectDB();
              
              String treatment_id=treatmentid.getSelectedItem().toString();
              String patient_id=patientid.getSelectedItem().toString();
              String doctor_id=doctorid.getSelectedItem().toString();
              String start_date=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();//covert date to string
              String end_date=((JTextField)jDateChooser3.getDateEditor().getUiComponent()).getText();
              String treat_status=status.getText();
              System.out.println(start_date);
              System.out.println(end_date);
              PreparedStatement ps1=con.prepareStatement("INSERT INTO treatment_book(treatmentbookid,treatmentid,patientid,doctorid,start_date,end_date,status) VALUES(?,?,?,?,?,?,?)");
              ps1.setString(1,treatmentbook_id);
              ps1.setString(2,treatment_id);
              ps1.setString(3,patient_id);
              ps1.setString(4,doctor_id);
              ps1.setString(5,start_date);
              ps1.setString(6,end_date);
              ps1.setString(7,treat_status);
              ps1.executeUpdate();
              JOptionPane.showMessageDialog(null,"Inserted suncessfully..");
              autoID();
              RefrushTable();
              treatmentid.setSelectedItem(null);
              doctorid.setSelectedItem(null);
              patientid.setSelectedItem(null);
              jDateChooser2.setDate(null);
              jDateChooser3.setDate(null);
              status.setText(null);
              
            }
            catch(Exception ex){
               JOptionPane.showMessageDialog(null,"error.try again...");
            }
        }

    }//GEN-LAST:event_insert_treatmentbookActionPerformed

    private void update_treatmentbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_treatmentbookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_treatmentbookMouseClicked

    private void update_treatmentbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_treatmentbookActionPerformed
        // TODO add your handling code here:
        String treatmentbook_id=treatmentbookid.getText();
        if(treatmentbookid.getText().equals("") || status.getText().equals("")){
            JOptionPane.showMessageDialog(null,"All fields are required..");
        }
        else{
            try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
            
               String treatment_id=treatmentid.getSelectedItem().toString();
               String patient_id=patientid.getSelectedItem().toString();
               String doctor_id=doctorid.getSelectedItem().toString();
               String start_date=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();//covert date to string
               String end_date=((JTextField)jDateChooser3.getDateEditor().getUiComponent()).getText();
               String treat_status=status.getText();
               PreparedStatement ps=con.prepareStatement("UPDATE treatment_book SET treatmentid=?,patientid=?,doctorid=?,start_date=?,end_date=?,status=? WHERE treatmentbookid=?");
                ps.setString(1,treatment_id);
                ps.setString(2,patient_id);
                ps.setString(3,doctor_id);
                ps.setString(4, start_date);
                ps.setString(5,end_date);
                ps.setString(6,treat_status);
                ps.setString(7,treatmentbook_id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"updated suncessfully..");
                autoID();
                RefrushTable();
            }
            catch(Exception ex){
               JOptionPane.showMessageDialog(null,"Please enter id and details to update!!");
               autoID();
            }
        }
    }//GEN-LAST:event_update_treatmentbookActionPerformed

    private void delete_treatmentbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_treatmentbookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_treatmentbookMouseClicked

    private void delete_treatmentbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_treatmentbookActionPerformed
        // TODO add your handling code here:
        String treatmentbook_id=treatmentbookid.getText();
        if(treatmentbookid.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Enter ID to delete..");
        }
        else{
           try{
              connection mysql=new connection();
              Connection con=mysql.connectDB();
              PreparedStatement ps=con.prepareStatement("DELETE from treatment_book WHERE treatmentbookid=?");
              ps.setString(1,treatmentbook_id);
              ps.executeUpdate();
              JOptionPane.showMessageDialog(null,"deleted suncessfully..");
              autoID();
              RefrushTable();
           }
           catch(Exception ex){
              JOptionPane.showMessageDialog(null,"error happen.please try again..");
              autoID(); 
           }
        }
    }//GEN-LAST:event_delete_treatmentbookActionPerformed

    private void treatmentbookidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treatmentbookidMouseClicked
        // TODO add your handling code here:
        String query=treatmentbookid.getText();
        filter(query);
    }//GEN-LAST:event_treatmentbookidMouseClicked

    private void treatmentbook_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treatmentbook_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentbook_tableMouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
        new manager_appointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        // TODO add your handling code here:
        new manager_treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here:
        new manager_room().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // TODO add your handling code here:
        new manager_treatment_book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
        new manager_room_book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        new manager_payment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel46MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new manager_dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_treatment_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_treatment_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_treatment_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_treatment_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_treatment_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_treatmentbook;
    private javax.swing.JLabel close;
    private javax.swing.JButton delete_treatmentbook;
    private javax.swing.JComboBox<String> doctorid;
    private javax.swing.JTextField enddate;
    private javax.swing.JLabel home;
    private javax.swing.JButton insert_treatmentbook;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> patientid;
    private javax.swing.JButton search_treatmentbook;
    private javax.swing.JTextField startdate;
    private javax.swing.JTextField status;
    private javax.swing.JTable treatmentbook_table;
    private javax.swing.JTextField treatmentbookid;
    private javax.swing.JComboBox<String> treatmentid;
    private javax.swing.JButton update_treatmentbook;
    // End of variables declaration//GEN-END:variables
}
