/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package family_dental_care;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thoma
 */
public class manager_treatment extends javax.swing.JFrame {

    /**
     * Creates new form manager_treatment
     */
    public manager_treatment() {
        initComponents();
        autoID();
        sort();
        RefrushTable();
    Toolkit toolkit=getToolkit();
    Dimension size=toolkit.getScreenSize();
    setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    
    ImageIcon logo_im=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    Image img1_logo=logo_im.getImage();
    Image img2_logo=img1_logo.getScaledInstance(logo.getWidth(),logo.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon a=new ImageIcon(img2_logo);
    logo.setIcon(a);
    
    ImageIcon home_im=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("home.png")));
    Image img1_home=home_im.getImage();
    Image img2_home=img1_home.getScaledInstance(home.getWidth(),home.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon b=new ImageIcon(img2_home);
    home.setIcon(b);
    
    
    //resize close button 
    ImageIcon close_img=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("close.png")));
    Image img1_close=close_img.getImage();
    Image img2_close=img1_close.getScaledInstance(close.getWidth(),close.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon c=new ImageIcon(img2_close);
    close.setIcon(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        treatmentid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        clear_treatment = new javax.swing.JButton();
        search_treatment = new javax.swing.JButton();
        insert_treatment = new javax.swing.JButton();
        update_treatment = new javax.swing.JButton();
        delete_treatment = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        treatmenttype = new javax.swing.JComboBox<>();
        roomtype = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        treatment_table = new javax.swing.JTable();
        home = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 194, 213));

        jLabel29.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel29.setText("            Doctor");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel30.setText("            Patient");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel31.setText("      Appointment");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel32.setText("              Staff");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel33.setText("         Treatment");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel34.setText("             Room");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel35.setText("    Treatment Book");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel36.setText("        Room Book");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel37.setText("           Payment");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setText("Treatment");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel11.setText("Treatment ID");

        treatmentid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        treatmentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentidActionPerformed(evt);
            }
        });
        treatmentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                treatmentidKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel13.setText("Treatment Type");

        clear_treatment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        clear_treatment.setText("clear");
        clear_treatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_treatmentMouseClicked(evt);
            }
        });
        clear_treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_treatmentActionPerformed(evt);
            }
        });

        search_treatment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        search_treatment.setText("search");
        search_treatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_treatmentMouseClicked(evt);
            }
        });
        search_treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_treatmentActionPerformed(evt);
            }
        });

        insert_treatment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        insert_treatment.setText("insert");
        insert_treatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insert_treatmentMouseClicked(evt);
            }
        });
        insert_treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_treatmentActionPerformed(evt);
            }
        });

        update_treatment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        update_treatment.setText("update");
        update_treatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_treatmentMouseClicked(evt);
            }
        });
        update_treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_treatmentActionPerformed(evt);
            }
        });

        delete_treatment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        delete_treatment.setText("delete");
        delete_treatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_treatmentMouseClicked(evt);
            }
        });
        delete_treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_treatmentActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel14.setText("Room Type");

        treatmenttype.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        treatmenttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dental checkups", "Professional teeth cleaning", "Fissure sealants", "Fillings", "Dental fillings", "Resotring teeth", "Root canal treatment", "Orthodontic treatment", "Mouthguards", "Tooth removal" }));
        treatmenttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmenttypeActionPerformed(evt);
            }
        });

        roomtype.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surgery", "Scan" }));
        roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtypeActionPerformed(evt);
            }
        });

        treatment_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Treatment type", "Room type"
            }
        ));
        treatment_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treatment_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treatment_table);

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(treatmentid)
                                    .addComponent(treatmenttype, 0, 179, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(56, 56, 56)
                                .addComponent(roomtype, 0, 179, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(clear_treatment, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(search_treatment, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(insert_treatment, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(update_treatment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_treatment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(treatmentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_treatment))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(treatmenttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(search_treatment)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(insert_treatment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update_treatment)))
                .addGap(14, 14, 14)
                .addComponent(delete_treatment)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void autoID(){
        try{
        connection mysql=new connection();
        Connection con=mysql.connectDB();
        PreparedStatement selectdata=con.prepareStatement("SELECT treatmentid FROM treatment ORDER BY treatmentid DESC LIMIT 1");
        ResultSet rs=selectdata.executeQuery();
        if(rs.next()){
           String rnno=rs.getString("treatmentid");
           int co=rnno.length();
           String txt= rnno.substring(0, 3);
           String num=rnno.substring(3, co);
           int n=Integer.parseInt(num);
           n++;
           String snum=Integer.toString(n);
           String ftxt=txt+snum;
           treatmentid.setText(ftxt);
        }
        else{
           treatmentid.setText("T001");
        }
        }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null,"no id is there..");
        }
    }
    //LOAD DATA TO TABLE
    private void RefrushTable(){
    try{
         connection mysql=new connection();
         Connection con=mysql.connectDB();
         PreparedStatement ps1=con.prepareStatement("SELECT * FROM treatment");
         ResultSet rs=ps1.executeQuery();
         DefaultTableModel model=(DefaultTableModel)treatment_table.getModel();
         model.setRowCount(0);
         while(rs.next()){
           String treatment_id=rs.getString("treatmentid");
           String treatment_type=rs.getString("treatmenttype");
           String room_type=rs.getString("roomtype");
           //create array for store data into patient_table
           String tbData[]={treatment_id,treatment_type,room_type};
           DefaultTableModel tb1Model=(DefaultTableModel)treatment_table.getModel();
           //add string array data to table
           tb1Model.addRow(tbData);                   
         }
         
        }
        catch(Exception ex){
         JOptionPane.showMessageDialog(null,"error happen.please try again..");
         autoID();
        }
    }
    //Sort table
    private void sort(){
       DefaultTableModel model=(DefaultTableModel)treatment_table.getModel();    
       TableRowSorter sorter=new TableRowSorter(model);
       treatment_table.setRowSorter(sorter);
    }
    //Filter table with sorting object
    private void filter(String query){
       //sorting the table values
       DefaultTableModel model=(DefaultTableModel)treatment_table.getModel();    
       TableRowSorter sorter=new TableRowSorter(model);
       treatment_table.setRowSorter(sorter);
       sorter.setRowFilter(RowFilter.regexFilter(query));
       
    }
    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        new manager_doctor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        new patient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        new manager_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void treatmentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentidActionPerformed

    private void treatmentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_treatmentidKeyReleased
        String query=treatmentid.getText();
        filter(query);
    }//GEN-LAST:event_treatmentidKeyReleased

    private void clear_treatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_treatmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_treatmentMouseClicked

    private void clear_treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_treatmentActionPerformed
        // TODO add your handling code here:
        treatmenttype.setSelectedItem(null);
        roomtype.setSelectedItem(null);
        autoID();
        
    }//GEN-LAST:event_clear_treatmentActionPerformed

    private void search_treatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_treatmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_search_treatmentMouseClicked

    private void search_treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_treatmentActionPerformed
        // TODO add your handling code here:
        String treatment_id=treatmentid.getText();
        if(treatmentid.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Please enter ID to search..");
        }
        else{
           try{
            connection mysql=new connection();
            Connection con=mysql.connectDB();
            
            PreparedStatement selectdata=con.prepareStatement("select * from treatment where treatmentid=?");
            selectdata.setString(1,treatment_id);
            ResultSet rs=selectdata.executeQuery();
            if(rs.next()){
                treatmentid.setText(rs.getString("treatmentid"));
                String treatment_type=rs.getString("treatmenttype");
                treatmenttype.setSelectedItem(treatment_type);
                String room_type=rs.getString("roomtype");
                roomtype.setSelectedItem(room_type);
                
                
            }
            else{
                roomtype.setSelectedItem(null);
                treatmenttype.setSelectedItem(null);
                JOptionPane.showMessageDialog(null,"no records are there!!");
                autoID();
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"error happen.please try again..");
            autoID();
        }
        }
    }//GEN-LAST:event_search_treatmentActionPerformed

    private void insert_treatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_treatmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_insert_treatmentMouseClicked

    private void insert_treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_treatmentActionPerformed
        // TODO add your handling code here:
        if(treatmentid.getText().equals("")){
           JOptionPane.showMessageDialog(null,"All the fields are required..");
           autoID();
        }
        else{
           try{
           connection mysql=new connection();
           Connection con=mysql.connectDB();
           String treatment_id=treatmentid.getText();
           String treatment_type=treatmenttype.getSelectedItem().toString();
           String room_type=roomtype.getSelectedItem().toString();
           PreparedStatement ps1=con.prepareStatement("INSERT INTO treatment(treatmentid,treatmenttype,roomtype) VALUES(?,?,?)");
           ps1.setString(1,treatment_id);
           ps1.setString(2,treatment_type);
           ps1.setString(3,room_type);
           ps1.executeUpdate();
           JOptionPane.showMessageDialog(null,"Inserted suncessfully..");
           autoID();
           RefrushTable();
           
        }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null,"Please try again..");
           autoID();
        }
        }
    }//GEN-LAST:event_insert_treatmentActionPerformed

    private void update_treatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_treatmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_treatmentMouseClicked

    private void update_treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_treatmentActionPerformed
        // TODO add your handling code here:
        if(treatmentid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"All the fields are required..");
            autoID();
        }
        else{
           try{

             connection mysql=new connection();
             Connection con=mysql.connectDB();
             String treatment_id=treatmentid.getText();
             String treatment_type=treatmenttype.getSelectedItem().toString();
             String room_type=roomtype.getSelectedItem().toString();
             PreparedStatement ps=con.prepareStatement("UPDATE treatment SET treatmenttype=?,roomtype=? WHERE treatmentid=?");
             ps.setString(1,treatment_type);
             ps.setString(2,room_type);
             ps.setString(3,treatment_id);
             ps.executeUpdate();
             JOptionPane.showMessageDialog(null,"updated suncessfully..");
             autoID();
             RefrushTable();
        }
        catch(Exception ex){
               JOptionPane.showMessageDialog(null,"Please enter id and details to update!!");
               autoID();
        }
        }
    }//GEN-LAST:event_update_treatmentActionPerformed

    private void delete_treatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_treatmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_treatmentMouseClicked

    private void delete_treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_treatmentActionPerformed
        // TODO add your handling code here:
        String treatment_id=treatmentid.getText();
        if(treatment_id.equals("")){
           JOptionPane.showMessageDialog(null,"Enter ID to delete..");
           autoID();
        }
        else{
            try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
               PreparedStatement ps=con.prepareStatement("DELETE from treatment WHERE treatmentid=?");
               ps.setString(1,treatment_id);
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null,"deleted suncessfully..");
               autoID();
               RefrushTable();
               
            }
            catch(Exception ex){
               JOptionPane.showMessageDialog(null,"error happen.please try again..");
               autoID();
            }
        }
    }//GEN-LAST:event_delete_treatmentActionPerformed

    private void treatmenttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmenttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmenttypeActionPerformed

    private void roomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomtypeActionPerformed

    private void treatment_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treatment_tableMouseClicked
        // TODO add your handling code here:
        
        int i=treatment_table.getSelectedRow();
        TableModel model=treatment_table.getModel();
        treatmentid.setText((String) model.getValueAt(i,0));
        String treatment_type=model.getValueAt(i,1).toString();
        treatmenttype.setSelectedItem(treatment_type); 
        String room_type=model.getValueAt(i,2).toString();
        roomtype.setSelectedItem(room_type);        
    }//GEN-LAST:event_treatment_tableMouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        new manager_appointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        new manager_treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        new manager_room().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        new manager_treatment_book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        new manager_room_book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
        new manager_payment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel37MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new manager_dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_treatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_treatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_treatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_treatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_treatment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_treatment;
    private javax.swing.JLabel close;
    private javax.swing.JButton delete_treatment;
    private javax.swing.JLabel home;
    private javax.swing.JButton insert_treatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> roomtype;
    private javax.swing.JButton search_treatment;
    private javax.swing.JTable treatment_table;
    private javax.swing.JTextField treatmentid;
    private javax.swing.JComboBox<String> treatmenttype;
    private javax.swing.JButton update_treatment;
    // End of variables declaration//GEN-END:variables
}
