/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package family_dental_care;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thoma
 */
public class manager_staff extends javax.swing.JFrame {

    /**
     * Creates new form manager_staff
     */
    public manager_staff() {
        initComponents();
        RefrushTable();
        autoID();
        sort();
    Toolkit toolkit=getToolkit();
    Dimension size=toolkit.getScreenSize();
    setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    
    ImageIcon logo_im=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    Image img1_logo=logo_im.getImage();
    Image img2_logo=img1_logo.getScaledInstance(logo.getWidth(),logo.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon a=new ImageIcon(img2_logo);
    logo.setIcon(a);
    
    ImageIcon home_im=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("home.png")));
    Image img1_home=home_im.getImage();
    Image img2_home=img1_home.getScaledInstance(home.getWidth(),home.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon b=new ImageIcon(img2_home);
    home.setIcon(b);
    
    
    //resize close button 
    ImageIcon close_img=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("close.png")));
    Image img1_close=close_img.getImage();
    Image img2_close=img1_close.getScaledInstance(close.getWidth(),close.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon c=new ImageIcon(img2_close);
    close.setIcon(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gender_male = new javax.swing.JRadioButton();
        gender_female = new javax.swing.JRadioButton();
        staffphonenumber = new javax.swing.JTextField();
        staffnic = new javax.swing.JTextField();
        staffaddress = new javax.swing.JTextField();
        staffname = new javax.swing.JTextField();
        staffid = new javax.swing.JTextField();
        clear_staff = new javax.swing.JButton();
        search_staff = new javax.swing.JButton();
        insertstaff = new javax.swing.JButton();
        updatestaff = new javax.swing.JButton();
        deletestaff = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        stafftype = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        staff_table = new javax.swing.JTable();
        home = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 194, 213));

        jLabel29.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel29.setText("            Doctor");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel30.setText("            Patient");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel31.setText("      Appointment");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel32.setText("              Staff");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel33.setText("         Treatment");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel34.setText("             Room");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel35.setText("    Treatment Book");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel36.setText("        Room Book");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel37.setText("           Payment");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setText("Staff");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Staff ID");

        jLabel3.setBackground(new java.awt.Color(87, 194, 213));
        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel3.setText("Staff Name");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel5.setText("Staff NIC");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel6.setText("Mobile Number");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel10.setText("Gender");

        buttonGroup1.add(gender_male);
        gender_male.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        gender_male.setText("Male");

        buttonGroup1.add(gender_female);
        gender_female.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        gender_female.setText("Female");

        staffphonenumber.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        staffnic.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        staffaddress.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        staffaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffaddressActionPerformed(evt);
            }
        });

        staffname.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        staffname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffnameActionPerformed(evt);
            }
        });
        staffname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                staffnameKeyReleased(evt);
            }
        });

        staffid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        staffid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                staffidKeyReleased(evt);
            }
        });

        clear_staff.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        clear_staff.setText("clear");
        clear_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_staffMouseClicked(evt);
            }
        });
        clear_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_staffActionPerformed(evt);
            }
        });

        search_staff.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        search_staff.setText("search");
        search_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_staffActionPerformed(evt);
            }
        });

        insertstaff.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        insertstaff.setText("insert");
        insertstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertstaffActionPerformed(evt);
            }
        });

        updatestaff.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        updatestaff.setText("update");
        updatestaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatestaffActionPerformed(evt);
            }
        });

        deletestaff.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        deletestaff.setText("delete");
        deletestaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestaffActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel7.setText("Staff Type");

        stafftype.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        stafftype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Nurse", "Receptionist" }));

        staff_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "NIC", "Contact No", "Staff Type", "Gender"
            }
        ));
        staff_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(staff_table);

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(gender_male, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gender_female))
                                    .addComponent(staffnic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(staffaddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(staffname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(staffid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(staffphonenumber)
                                            .addComponent(stafftype, 0, 212, Short.MAX_VALUE))))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clear_staff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search_staff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(insertstaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updatestaff, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deletestaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(staffname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(staffphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(stafftype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(clear_staff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_staff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertstaff)
                        .addGap(12, 12, 12)
                        .addComponent(updatestaff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletestaff)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_male)
                    .addComponent(gender_female)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void autoID(){
        try{
        connection mysql=new connection();
        Connection con=mysql.connectDB();
        PreparedStatement selectdata=con.prepareStatement("SELECT staffid FROM staff ORDER BY staffid DESC LIMIT 1");
        ResultSet rs=selectdata.executeQuery();
        if(rs.next()){
           String rnno=rs.getString("staffid");
           int co=rnno.length();
           String txt= rnno.substring(0, 3);
           String num=rnno.substring(3, co);
           int n=Integer.parseInt(num);
           n++;
           String snum=Integer.toString(n);
           String ftxt=txt+snum;
           staffid.setText(ftxt);
        }
        else{
           staffid.setText("S001");
        }
        }
        catch(Exception ex){
         
        }
    }
    //load data to table
    private void RefrushTable(){
    try{
         connection mysql=new connection();
         Connection con=mysql.connectDB();
         PreparedStatement ps1=con.prepareStatement("SELECT * FROM staff");
         ResultSet rs=ps1.executeQuery();
         DefaultTableModel model=(DefaultTableModel)staff_table.getModel();
         model.setRowCount(0);
         while(rs.next()){
           String staff_id=rs.getString("staffid");
           String staff_name=rs.getString("staffname");
           String staff_address=rs.getString("staffaddress");
           String staff_nic=rs.getString("staffnic");
           String contact_no=rs.getString("contactno");
           String staff_type=rs.getString("stafftype");
           String staff_gender=rs.getString("gender");
           //create array for store data into patient_table
           String tbData[]={staff_id,staff_name,staff_address,staff_nic,contact_no,staff_type,staff_gender};
           DefaultTableModel tb1Model=(DefaultTableModel)staff_table.getModel();
           //add string array data to table
           tb1Model.addRow(tbData);                   
         }
         
        }
        catch(Exception ex){
         JOptionPane.showMessageDialog(null,"error happen.please try again..");
         autoID();
        }
    }
    //Sort table
    private void sort(){
       DefaultTableModel model=(DefaultTableModel)staff_table.getModel();    
       TableRowSorter sorter=new TableRowSorter(model);
       staff_table.setRowSorter(sorter);
    }
    //Filter table with sorting object
    private void filter(String query){
       //sorting the table values
       DefaultTableModel model=(DefaultTableModel)staff_table.getModel();    
       TableRowSorter sorter=new TableRowSorter(model);
       staff_table.setRowSorter(sorter);
       sorter.setRowFilter(RowFilter.regexFilter(query));
       
    }
    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        new patient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void staffaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffaddressActionPerformed

    private void staffnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffnameActionPerformed

    private void staffnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_staffnameKeyReleased
        //String query=staffname.getText();
        //filter(query);
    }//GEN-LAST:event_staffnameKeyReleased

    private void clear_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_staffMouseClicked
        // TODO add your handling code here:
        autoID();
        staffname.setText(null);
        staffaddress.setText(null);
        staffnic.setText(null);
        staffphonenumber.setText(null);
        stafftype.setSelectedItem(false);
        gender_male.setSelected(false);
        gender_female.setSelected(false);
    }//GEN-LAST:event_clear_staffMouseClicked

    private void clear_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_staffActionPerformed

    private void search_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_staffActionPerformed
        // TODO add your handling code here:
        String staff_id=staffid.getText();
        if(staffid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter ID to search..");
        }
        else{
            try{
                connection mysql=new connection();
                Connection con=mysql.connectDB();

                PreparedStatement selectdata=con.prepareStatement("select * from staff where staffid=?");
            selectdata.setString(1,staff_id);
            ResultSet rs=selectdata.executeQuery();
            if(rs.next()){
                staffname.setText(rs.getString("staffname"));
                staffaddress.setText(rs.getString("staffaddress"));
                staffnic.setText(rs.getString("staffnic"));
                staffphonenumber.setText(rs.getString("contactno"));
                String staff_type=rs.getString("stafftype");
                    switch(staff_type) {
                        case "Manager":
                            stafftype.setSelectedItem("Manager");
                            break;
                        case "Nurse":
                            stafftype.setSelectedItem("Nurse");
                            break;
                        case "Receptionist":
                            stafftype.setSelectedItem("Receptionist");                
                            break;
                        default:
                            break;
                    }
                if(rs.getString("gender").equals("Male")){
                    gender_male.setSelected(true);
                    gender_female.setSelected(false);
                    
                }
                else if(rs.getString("gender").equals("Female")){
                    gender_female.setSelected(true);
                    gender_male.setSelected(false);
                    
                }

            }
            else{
                staffname.setText(null);
                staffaddress.setText(null);
                staffnic.setText(null);
                staffphonenumber.setText(null);
                stafftype.setSelectedItem(false);
                gender_male.setSelected(false);
                gender_female.setSelected(false);
                JOptionPane.showMessageDialog(null,"no records are there!!");
                autoID();
            }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,"error happen.please try again..");
                autoID();
            }
        }
    }//GEN-LAST:event_search_staffActionPerformed

    private void insertstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertstaffActionPerformed
        if(staffid.getText().equals("") || staffname.getText().equals("") || staffaddress.getText().equals("") || staffnic.getText().equals("") || staffphonenumber.getText().equals("")){
            JOptionPane.showMessageDialog(null,"All the fields are requried..");
        }
        else{
            try{
                connection mysql=new connection();
                Connection con=mysql.connectDB();
                String staff_id=staffid.getText();
                String staff_name=staffname.getText();
                String staff_address=staffaddress.getText();
                String staff_nic=staffnic.getText();
                String staff_phonenumber=staffphonenumber.getText();
                String staff_type=stafftype.getSelectedItem().toString();
                    PreparedStatement ps1=con.prepareStatement("INSERT INTO staff(staffid,staffname,staffaddress,staffnic,contactno,stafftype,gender) VALUES(?,?,?,?,?,?,?)");
                    ps1.setString(1,staff_id);
                    ps1.setString(2,staff_name);
                    ps1.setString(3,staff_address);
                    ps1.setString(4,staff_nic);
                    ps1.setString(5,staff_phonenumber);
                    ps1.setString(6,staff_type);
                    if(gender_male.isSelected()){
                        ps1.setString(7,gender_male.getText());
                        ps1.executeUpdate();
                    }
                    else{
                        ps1.setString(7,gender_female.getText());
                        ps1.executeUpdate();
                    }

                    JOptionPane.showMessageDialog(null,"Inserted suncessfully..");
                    autoID();
                    RefrushTable();
                    staffname.setText(null);
                    staffaddress.setText(null);
                    staffnic.setText(null);
                    staffphonenumber.setText(null);
                    stafftype.setSelectedItem(false);
                    gender_male.setSelected(false);
                    gender_female.setSelected(false);
                    
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,"Please enter details..");
                autoID();
            }
        }
    }//GEN-LAST:event_insertstaffActionPerformed

    private void updatestaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatestaffActionPerformed
        // TODO add your handling code here:
        String staff_id=staffid.getText();
        if(staffid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter id to update!!");
            autoID();
        }
        else{
            try{
                connection mysql=new connection();
                Connection con=mysql.connectDB();
                String staff_name=staffname.getText();
                String staff_address=staffaddress.getText();
                String staff_nic=staffnic.getText();
                String staff_phonenumber=staffphonenumber.getText();
                String staff_type=stafftype.getSelectedItem().toString();
                String staff_gender;
                if(gender_male.isSelected()){
                    staff_gender=gender_male.getText();
                }
                else{
                    staff_gender=gender_female.getText();
                }
                if(staffname.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"Please enter id to update!!");
                    autoID();
                }
                else{
                    PreparedStatement ps=con.prepareStatement("UPDATE staff SET staffname=?,staffaddress=?,staffnic=?,contactno=?,stafftype=?,gender=? WHERE staffid=?");
                    ps.setString(1,staff_name);
                    ps.setString(2,staff_address);
                    ps.setString(3,staff_nic);
                    ps.setString(4, staff_phonenumber);
                    ps.setString(5,staff_type);
                    ps.setString(6,staff_gender);
                    ps.setString(7,staff_id);
                    ps.executeUpdate();
                    staffname.setText(null);
                    staffaddress.setText(null);
                    staffnic.setText(null);
                    staffphonenumber.setText(null);
                    stafftype.setSelectedItem(false);
                    gender_male.setSelected(false);
                    gender_female.setSelected(false);
                    JOptionPane.showMessageDialog(null,"updated suncessfully..");
                    autoID();
                    RefrushTable();
                }
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,"Please enter id and details to update!!");
                autoID();
            }
        }
    }//GEN-LAST:event_updatestaffActionPerformed

    private void deletestaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestaffActionPerformed
        // TODO add your handling code here:

        try{
            connection mysql=new connection();
            Connection con=mysql.connectDB();
            String staff_id=staffid.getText();
            if(staffid.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Enter ID to delete..");
                autoID();
            }
            else{
                PreparedStatement ps=con.prepareStatement("DELETE from staff WHERE staffid=?");
                ps.setString(1,staff_id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"deleted suncessfully..");
                autoID();
                RefrushTable();
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"error happen.please try again..");
            autoID();
        }
    }//GEN-LAST:event_deletestaffActionPerformed

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        new manager_staff().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel32MouseClicked

    private void staff_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_tableMouseClicked
        // TODO add your handling code here:
        int i=staff_table.getSelectedRow();
        TableModel model=staff_table.getModel();
        staffid.setText((String) model.getValueAt(i,0));
        staffname.setText((String) model.getValueAt(i,1));
        staffaddress.setText((String) model.getValueAt(i,2));
        staffnic.setText((String) model.getValueAt(i,3));
        staffphonenumber.setText((String) model.getValueAt(i,4));
        String staff_type=model.getValueAt(i,5).toString();
        stafftype.setSelectedItem(staff_type);
        String staff_gender=model.getValueAt(i,6).toString();
        if(staff_gender.equals("Male")){
                    gender_male.setSelected(true);
                    gender_female.setSelected(false);
        }
        else if(staff_gender.equals("Female")){
                    gender_female.setSelected(true);
                    gender_male.setSelected(false);
       }
    
    }//GEN-LAST:event_staff_tableMouseClicked

    private void staffidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_staffidKeyReleased
        // TODO add your handling code here:
        String query=staffid.getText();
        filter(query);
    }//GEN-LAST:event_staffidKeyReleased

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        new manager_appointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        new manager_doctor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        new manager_treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        new manager_room().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        new manager_treatment_book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        new manager_room_book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new manager_dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear_staff;
    private javax.swing.JLabel close;
    private javax.swing.JButton deletestaff;
    private javax.swing.JRadioButton gender_female;
    private javax.swing.JRadioButton gender_male;
    private javax.swing.JLabel home;
    private javax.swing.JButton insertstaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton search_staff;
    private javax.swing.JTable staff_table;
    private javax.swing.JTextField staffaddress;
    private javax.swing.JTextField staffid;
    private javax.swing.JTextField staffname;
    private javax.swing.JTextField staffnic;
    private javax.swing.JTextField staffphonenumber;
    private javax.swing.JComboBox<String> stafftype;
    private javax.swing.JButton updatestaff;
    // End of variables declaration//GEN-END:variables
}
