/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package family_dental_care;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thoma
 */
public class manager_payment extends javax.swing.JFrame {

    /**
     * Creates new form manager_payment
     */
    public manager_payment() {
        initComponents();
        autoID();
        treatmentidcombobox();
        RefrushTable();
        sort();
        
        //center the frame
    Toolkit toolkit=getToolkit();
    Dimension size=toolkit.getScreenSize();
    setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    
    ImageIcon logo_im=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    Image img1_logo=logo_im.getImage();
    Image img2_logo=img1_logo.getScaledInstance(logo.getWidth(),logo.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon a=new ImageIcon(img2_logo);
    logo.setIcon(a);
    
    ImageIcon home_im=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("home.png")));
    Image img1_home=home_im.getImage();
    Image img2_home=img1_home.getScaledInstance(home.getWidth(),home.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon b=new ImageIcon(img2_home);
    home.setIcon(b);
    
    
    //resize close button 
    ImageIcon close_img=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("close.png")));
    Image img1_close=close_img.getImage();
    Image img2_close=img1_close.getScaledInstance(close.getWidth(),close.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon c=new ImageIcon(img2_close);
    close.setIcon(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paymentid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        clear_payment = new javax.swing.JButton();
        search_payment = new javax.swing.JButton();
        insert_payment = new javax.swing.JButton();
        update_payment = new javax.swing.JButton();
        delete_payment = new javax.swing.JButton();
        check_doctors = new javax.swing.JButton();
        patientid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        treatmentfees = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        roomfees = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        payment_table = new javax.swing.JTable();
        treatmentbookid = new javax.swing.JComboBox<>();
        home = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(87, 194, 213));

        jLabel29.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel29.setText("            Doctor");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel30.setText("            Patient");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel31.setText("      Appointment");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel32.setText("              Staff");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel33.setText("         Treatment");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel34.setText("             Room");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel35.setText("    Treatment Book");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel36.setText("        Room Book");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel37.setText("           Payment");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setText("Payment");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel11.setText("Payment ID");

        paymentid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        paymentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentidActionPerformed(evt);
            }
        });
        paymentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentidKeyReleased(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(87, 194, 213));
        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel12.setText("TreatmentBook ID");

        clear_payment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        clear_payment.setText("clear");
        clear_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_paymentMouseClicked(evt);
            }
        });
        clear_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_paymentActionPerformed(evt);
            }
        });

        search_payment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        search_payment.setText("search");
        search_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_paymentActionPerformed(evt);
            }
        });

        insert_payment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        insert_payment.setText("insert");
        insert_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_paymentActionPerformed(evt);
            }
        });

        update_payment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        update_payment.setText("update");
        update_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_paymentActionPerformed(evt);
            }
        });

        delete_payment.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        delete_payment.setText("delete");
        delete_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_paymentActionPerformed(evt);
            }
        });

        check_doctors.setBackground(new java.awt.Color(204, 204, 204));
        check_doctors.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        check_doctors.setText("Access Details");
        check_doctors.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        check_doctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_doctorsActionPerformed(evt);
            }
        });

        patientid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        patientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientidActionPerformed(evt);
            }
        });
        patientid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patientidKeyReleased(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(87, 194, 213));
        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel13.setText("Patient ID");

        jLabel14.setBackground(new java.awt.Color(87, 194, 213));
        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel14.setText("Treatment Fees");

        treatmentfees.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        treatmentfees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentfeesActionPerformed(evt);
            }
        });
        treatmentfees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                treatmentfeesKeyReleased(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(87, 194, 213));
        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel15.setText("Room Fees");

        roomfees.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        roomfees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomfeesActionPerformed(evt);
            }
        });
        roomfees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roomfeesKeyReleased(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(87, 194, 213));
        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel16.setText("Total");

        total.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
        });

        description.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descriptionKeyReleased(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(87, 194, 213));
        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel17.setText("Description");

        payment_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient ID", "Doctor ID", "Date", "Time", "Fees", "Status"
            }
        ));
        jScrollPane1.setViewportView(payment_table);

        treatmentbookid.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        treatmentbookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentbookidActionPerformed(evt);
            }
        });

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(roomfees)
                                .addGap(186, 186, 186))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 7, Short.MAX_VALUE)
                                                .addComponent(check_doctors)
                                                .addGap(67, 67, 67))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(patientid, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                    .addComponent(paymentid, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(treatmentbookid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clear_payment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(search_payment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(update_payment, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(insert_payment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(treatmentfees)
                                        .addGap(62, 62, 62)
                                        .addComponent(delete_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(description, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total))
                                .addGap(186, 186, 186))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clear_payment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_payment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insert_payment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update_payment))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(treatmentbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(paymentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check_doctors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_payment)
                    .addComponent(jLabel14)
                    .addComponent(treatmentfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void autoID(){
        try{
        connection mysql=new connection();
        Connection con=mysql.connectDB();
        PreparedStatement selectdata=con.prepareStatement("SELECT paymentid FROM payment ORDER BY paymentid DESC LIMIT 1");
        ResultSet rs=selectdata.executeQuery();
        if(rs.next()){
           String rnno=rs.getString("paymentid");
           int co=rnno.length();
           String txt= rnno.substring(0, 3);
           String num=rnno.substring(3, co);
           int n=Integer.parseInt(num);
           n++;
           String snum=Integer.toString(n);
           String ftxt=txt+snum;
           paymentid.setText(ftxt);
        }
        else{
           paymentid.setText("M001");
        }
        }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null,"no id is there..");
        }
    }
    //treatment id for combobox
    private void treatmentidcombobox(){
        try{
           connection mysql=new connection();
           Connection con=mysql.connectDB();
           PreparedStatement ps1=con.prepareStatement("select * from treatment_book ");
           ResultSet rs=ps1.executeQuery();
           while(rs.next()){
                  treatmentbookid.addItem(rs.getString("treatmentbookid"));
           }         
        }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null,"no id is there..");
        }
        
        
    }
    private void RefrushTable(){
    try{
         connection mysql=new connection();
         Connection con=mysql.connectDB();
         PreparedStatement ps1=con.prepareStatement("SELECT * FROM payment");
         ResultSet rs=ps1.executeQuery();
         DefaultTableModel model=(DefaultTableModel)payment_table.getModel();
         model.setRowCount(0);
         while(rs.next()){
           String payment_id =rs.getString("paymentid");
           String patient_id=rs.getString("patientid");
           String treatmentbook_id=rs.getString("treatmentbookid");
           String pay_description=rs.getString("description");
           String treatment_fees=rs.getString("treatmentfees");
           String room_fees=rs.getString("roomfees");
           String total=rs.getString("total");
           //create array for store data into patient_table
           String tbData[]={payment_id,patient_id,treatmentbook_id,pay_description,treatment_fees,room_fees,total};
           DefaultTableModel tb1Model=(DefaultTableModel)payment_table.getModel();
           //add string array data to table
           tb1Model.addRow(tbData);                   
         }
         
        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null,"error happen.please try again..");
         autoID();
        }
    }
    private void sort(){
       DefaultTableModel model=(DefaultTableModel)payment_table.getModel();    
       TableRowSorter sorter=new TableRowSorter(model);
       payment_table.setRowSorter(sorter);
    }
    //Filter table with sorting object
    private void filter(String query){
       //sorting the table values
       DefaultTableModel model=(DefaultTableModel)payment_table.getModel();    
       TableRowSorter sorter=new TableRowSorter(model);
       payment_table.setRowSorter(sorter);
       sorter.setRowFilter(RowFilter.regexFilter(query));
       
    }
    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        new manager_doctor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        new patient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        new manager_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void paymentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentidActionPerformed

    private void paymentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentidKeyReleased
        String query=paymentid.getText();
        filter(query);
    }//GEN-LAST:event_paymentidKeyReleased

    private void clear_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_paymentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_paymentMouseClicked

    private void clear_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_paymentActionPerformed
        // TODO add your handling code here:
        treatmentbookid.setSelectedItem(null);
        patientid.setText(null);
        treatmentfees.setText(null);
        roomfees.setText(null);
        total.setText(null);
        description.setText(null);
        
    }//GEN-LAST:event_clear_paymentActionPerformed

    private void search_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_paymentActionPerformed
        // TODO add your handling code here:
        String payment_id=paymentid.getText();
        if(paymentid.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Enter ID to search..");    
        }
        else{
           try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
               PreparedStatement selectdata=con.prepareStatement("select * from payment where paymentid=?");
            selectdata.setString(1,payment_id);
            ResultSet rs=selectdata.executeQuery();
            if(rs.next()){
                paymentid.setText(rs.getString("paymentid"));
                String treatmentbook_id=rs.getString("treatmentbookid");
                treatmentbookid.setSelectedItem(treatmentbook_id);
                patientid.setText(rs.getString("patientid"));
                treatmentfees.setText(rs.getString("treatmentfees"));
                roomfees.setText(rs.getString("roomfees"));
                total.setText(rs.getString("total"));
                description.setText("description");
            }
            else{
                treatmentbookid.setSelectedItem(null);
                patientid.setText(null);
                treatmentfees.setText(null);
                roomfees.setText(null);
                total.setText(null);
                description.setText(null);
                JOptionPane.showMessageDialog(null,"no records are there!!");
                autoID();
            }
           }
           catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error..");
                autoID();
           }
        }
    }//GEN-LAST:event_search_paymentActionPerformed

    private void insert_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_paymentActionPerformed
        if(paymentid.getText().equals("") || treatmentfees.getText().equals("") || total.getText().equals("")){
             JOptionPane.showMessageDialog(null,"All the fields are required.."); 
             RefrushTable();
        }
        else{
            try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
               String payment_id=paymentid.getText();
               String treatment_bookid=treatmentbookid.getSelectedItem().toString();
               String patient_id=patientid.getText();
               String treatment_fees=treatmentfees.getText();
               Integer treat_fees=Integer.valueOf(treatment_fees);
               String room_fees=roomfees.getText();
               Integer r_fees=Integer.valueOf(room_fees);
               String total_fees=total.getText();
               Integer t_fees=Integer.valueOf(total_fees);
               String pay_descrip=description.getText();
               PreparedStatement ps1=con.prepareStatement("INSERT INTO payment(paymentid,patientid,treatmentbookid,description,treatmentfees,roomfees,total) VALUES(?,?,?,?,?,?,?)");
               ps1.setString(1,payment_id);
               ps1.setString(2,patient_id);
               ps1.setString(3,treatment_bookid);
               ps1.setString(4,pay_descrip);
               ps1.setInt(5,treat_fees);
               ps1.setInt(6,r_fees);
               ps1.setInt(7,t_fees);
               ps1.executeUpdate();
               JOptionPane.showMessageDialog(null,"Inserted suncessfully..");
               autoID();
               RefrushTable();
               treatmentbookid.setSelectedItem(null);
               patientid.setText(null);
               treatmentfees.setText(null);
               roomfees.setText(null);
               total.setText(null);
               description.setText(null);
            }
            catch(Exception ex){
               JOptionPane.showMessageDialog(null,"Error");
               RefrushTable();
            }
        }
    }//GEN-LAST:event_insert_paymentActionPerformed

    private void update_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_paymentActionPerformed
        // TODO add your handling code here:
        if(paymentid.getText().equals("")){
              JOptionPane.showMessageDialog(null,"Enter ID to update..");
              RefrushTable();    
        }
        else{
           try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
               String payment_id=paymentid.getText();
               String treatment_bookid=treatmentbookid.getSelectedItem().toString();
               String patient_id=patientid.getText();
               String treatment_fees=treatmentfees.getText();
               String room_fees=roomfees.getText();
               String total_fees=total.getText();
               String pay_descrip=description.getText();
               PreparedStatement ps=con.prepareStatement("UPDATE payment SET patientid=?,treatmentbookid=?,description=?,treatmentfees=?,roomfees=?,total=? WHERE paymentid=?");
               ps.setString(1,patient_id);
               ps.setString(2,treatment_bookid);
               ps.setString(3,pay_descrip);
               ps.setString(4,treatment_fees);
               ps.setString(5,room_fees);
               ps.setString(6,total_fees);
               ps.setString(7,payment_id);
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null,"updated suncessfully..");
               autoID();
               RefrushTable();
           }
           catch(Exception ex){
               JOptionPane.showMessageDialog(null,"Error");
               RefrushTable();
           }
        }
    }//GEN-LAST:event_update_paymentActionPerformed

    private void check_doctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_doctorsActionPerformed
        // TODO add your handling code here:
        String treatmentbook_id=treatmentbookid.getSelectedItem().toString();
        if(treatmentbookid.getSelectedItem().equals("")){
          JOptionPane.showMessageDialog(null,"Select ID to get details");
        }
        else{
            try{
               connection mysql=new connection();
               Connection con=mysql.connectDB();
               PreparedStatement ps1=con.prepareStatement("select * from treatment_book where treatmentbookid=?");
               ps1.setString(1,treatmentbook_id);
               ResultSet rs=ps1.executeQuery();
               while(rs.next()){
                  String patient_id=rs.getString("patientid");
                  patientid.setText(patient_id);
                  String treatment_id=rs.getString("treatmentid");
                  PreparedStatement ps2=con.prepareStatement("select * from room_book where patientid=?");
                  ps2.setString(1,patient_id);
                  ResultSet rs1=ps2.executeQuery();
                  if(rs1.next()){
                     String room_id=rs1.getString("roomid");
                     System.out.println(room_id);
                     String room_fees="450";
                     roomfees.setText(room_fees);
                     
                  }
                  else{
                    roomfees.setText("null");
                  }
                  PreparedStatement ps3=con.prepareStatement("select * from treatment where treatmentid=?");
                  ps3.setString(1,treatment_id);
                  ResultSet rs2=ps3.executeQuery();
                  while(rs2.next()){
                     String treat_descrip=rs2.getString("treatmenttype");
                     description.setText(treat_descrip);
                  }
                }
                RefrushTable();
               
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,"error happen.please try again..");
                autoID();
                RefrushTable();
            }
        }
        
    }//GEN-LAST:event_check_doctorsActionPerformed

    private void patientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientidActionPerformed

    private void patientidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_patientidKeyReleased

    private void treatmentfeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentfeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentfeesActionPerformed

    private void treatmentfeesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_treatmentfeesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentfeesKeyReleased

    private void roomfeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomfeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomfeesActionPerformed

    private void roomfeesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomfeesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_roomfeesKeyReleased

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyReleased

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void descriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionKeyReleased

    private void treatmentbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentbookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentbookidActionPerformed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        new manager_appointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        new manager_treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        new manager_room().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        new manager_treatment_book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        new manager_room_book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
        new manager_payment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel37MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new manager_dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void delete_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_paymentActionPerformed
        try{
            connection mysql=new connection();
            Connection con=mysql.connectDB();
            String payment_id=paymentid.getText();
            if(paymentid.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Enter ID to delete..");
                autoID();
                RefrushTable();
            }
            else{
                PreparedStatement ps=con.prepareStatement("DELETE from payment WHERE paymentid=?");
                ps.setString(1,payment_id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"deleted suncessfully..");
                autoID();
                RefrushTable();
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"error happen.please try again..");
            autoID();
            RefrushTable();
        }
    }//GEN-LAST:event_delete_paymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_doctors;
    private javax.swing.JButton clear_payment;
    private javax.swing.JLabel close;
    private javax.swing.JButton delete_payment;
    private javax.swing.JTextField description;
    private javax.swing.JLabel home;
    private javax.swing.JButton insert_payment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField patientid;
    private javax.swing.JTable payment_table;
    private javax.swing.JTextField paymentid;
    private javax.swing.JTextField roomfees;
    private javax.swing.JButton search_payment;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox<String> treatmentbookid;
    private javax.swing.JTextField treatmentfees;
    private javax.swing.JButton update_payment;
    // End of variables declaration//GEN-END:variables
}
